import Head from "next/head";
import type { AppProps } from "next/app";
import "@/styles/globals.scss";
import { inter } from "@/fonts";
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Kizbie</title>
      </Head>

      <main className={`${inter.className} overflow-hidden`}>
        <Component {...pageProps} />
      </main>
    </>
  );
}
